// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ebjA7b-inVvILUk7i-LEBTIohjLiWrQ',
    appId: '1:374960332576:web:aceec4de51313685220145',
    messagingSenderId: '374960332576',
    projectId: 'aura-estates-19b11',
    authDomain: 'aura-estates-19b11.firebaseapp.com',
    storageBucket: 'aura-estates-19b11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3mSJvEK0Zr30tOrYIs20JS6f0lrdmf5Y',
    appId: '1:374960332576:android:912d9835f64ba908220145',
    messagingSenderId: '374960332576',
    projectId: 'aura-estates-19b11',
    storageBucket: 'aura-estates-19b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAezXXXbOcq8f6rpt64F5jLFtHiJqcC5Ag',
    appId: '1:374960332576:ios:67f3cd096bf9d7d7220145',
    messagingSenderId: '374960332576',
    projectId: 'aura-estates-19b11',
    storageBucket: 'aura-estates-19b11.firebasestorage.app',
    iosBundleId: 'com.example.auraEstates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAezXXXbOcq8f6rpt64F5jLFtHiJqcC5Ag',
    appId: '1:374960332576:ios:67f3cd096bf9d7d7220145',
    messagingSenderId: '374960332576',
    projectId: 'aura-estates-19b11',
    storageBucket: 'aura-estates-19b11.firebasestorage.app',
    iosBundleId: 'com.example.auraEstates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ebjA7b-inVvILUk7i-LEBTIohjLiWrQ',
    appId: '1:374960332576:web:c2fd03109f096079220145',
    messagingSenderId: '374960332576',
    projectId: 'aura-estates-19b11',
    authDomain: 'aura-estates-19b11.firebaseapp.com',
    storageBucket: 'aura-estates-19b11.firebasestorage.app',
  );

}